name: dl-labs
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - numpy
  - pip
  - pip:
    - gymnasium
    - torch
    - torchvision
    - torchaudio
    - --extra-index-url https://download.pytorch.org/whl/cu126
variables:
  KMP_DUPLICATE_LIB_OK: "TRUE"